import { useEffect, useState } from 'react';
import { apiFetch, join } from './api.js';
import { useAuth } from './AuthContext.jsx';

const options = { genres:['مغامرة','دراما','تعليمي','خيال علمي','رعب لطيف'], styles:['3D','كرتون','أنمي','واقعي'], durations:[30,60,90,120] };

export default function App(){
 const { user, logout } = useAuth();
 const [idea,setIdea]=useState(''); const [genre,setGenre]=useState('مغامرة'); const [style,setStyle]=useState('3D'); const [duration,setDuration]=useState(60); const [projects,setProjects]=useState([]); const [active,setActive]=useState(null); const [busy,setBusy]=useState(false); const [error,setError]=useState('');
 const load=async()=>{try{const p=await apiFetch('/api/projects'); setProjects(p); setActive(a=>p.find(x=>x.id===a?.id)||p[0]||null)}catch(e){setError(e.message)}};
 useEffect(()=>{load(); const id=setInterval(load,3000); return()=>clearInterval(id)},[]);
 async function submit(e){e.preventDefault(); if(idea.trim().length<10){setError('اكتب فكرة لا تقل عن 10 أحرف.'); return} setBusy(true); setError(''); try{const p=await apiFetch('/api/projects',{method:'POST',body:JSON.stringify({idea,genre,style,duration})}); setProjects(x=>[p,...x]); setActive(p); setIdea('')}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function retry(){if(!active)return; try{await apiFetch(`/api/projects/${active.id}/retry`,{method:'POST'}); load()}catch(e){setError(e.message)}}
 return <main><header><div><span className="eyebrow">AI MOVIE STUDIO</span><h1>حوّل فكرتك إلى فيلم</h1><p>من سيناريو متماسك إلى فيديو جاهز للمشاهدة.</p></div><div className="header-actions"><div className="status"><i/> الاستوديو جاهز</div>{user&&<div className="account"><span>{user.email}</span><button className="link-button" onClick={logout}>تسجيل الخروج</button></div>}</div></header><section className="grid"><form className="panel composer" onSubmit={submit}><h2>ابدأ مشروعًا جديدًا</h2><label>فكرة الفيلم<textarea value={idea} onChange={e=>setIdea(e.target.value)} placeholder="مثال: طفل يكتشف مدينة سرية تحت البحر ويتعلم معنى الشجاعة…" /></label><div className="choices"><label>النوع<select value={genre} onChange={e=>setGenre(e.target.value)}>{options.genres.map(x=><option key={x}>{x}</option>)}</select></label><label>الأسلوب<select value={style} onChange={e=>setStyle(e.target.value)}>{options.styles.map(x=><option key={x}>{x}</option>)}</select></label><label>المدة<select value={duration} onChange={e=>setDuration(+e.target.value)}>{options.durations.map(x=><option key={x} value={x}>{x} ثانية</option>)}</select></label></div>{error&&<p className="error">{error}</p>}<button disabled={busy}>{busy?'نجهز مشروعك…':'إنشاء الفيلم ✦'}</button><small>يُحفظ المشروع تلقائيًا ويمكنك متابعة التقدم حتى لو أغلقت الصفحة.</small></form><aside className="panel steps"><span>خط الإنتاج</span>{['السيناريو وخطة المشاهد','ثبات الشخصيات والصور','التعليق الصوتي','التصدير النهائي'].map((x,i)=><div key={x}><b>0{i+1}</b>{x}</div>)}</aside></section><section className="workspace"><aside className="library"><h2>المشاريع</h2>{projects.length===0?<p>لا توجد مشاريع بعد.</p>:projects.map(p=><button className={active?.id===p.id?'selected':''} key={p.id} onClick={()=>setActive(p)}><strong>{p.title}</strong><small>{p.status==='complete'?'مكتمل':p.stage}</small></button>)}</aside><article className="panel project">{!active?<div className="empty">اكتب فكرة الفيلم للبدء.</div>:<><div className="project-head"><div><span className="eyebrow">{active.genre} · {active.style} · {active.duration} ثانية</span><h2>{active.title}</h2><p>{active.stage}</p></div><strong>{active.progress}%</strong></div><div className="progress"><i style={{width:`${active.progress}%`}}/></div>{active.status==='failed'&&<div className="error">{active.error}<button onClick={retry}>إعادة المحاولة</button></div>}{active.video_url&&<video controls src={join(active.video_url)}/>}<div className="scenes">{active.scenes.map(s=><figure key={s.id}>{s.image_url?<img src={join(s.image_url)} alt={s.description}/>:<div className="placeholder">المشهد {s.position}</div>}<figcaption><b>المشهد {s.position}</b><span>{s.narration}</span></figcaption></figure>)}</div>{active.script&&<details><summary>السيناريو</summary><p>{active.script}</p></details>}</>}</article></section></main>}
